### ISSUE TITLE
module not found gleam/map, moved to gleam/dict

### ISSUE THREAD

**Issue by adoublef** [JohnBjrk/adglent#1]
Seems that the type Map no longer exists, and instead its been moved to `import gleam/dict.{type Dict}` now

**Comment by JohnBjrk** [comment]
Thank you 🙏 

This seems to be (at least partially) a problem in the `showtime` submodule that was bundled with `adglent`. The plan is to fix this in the standalone `showtime` library and use the updated version in `adglent` instead
